module.exports = {
    'en' : 'English',
    'ca' : 'Catalan',
    'da' : 'Danish',
    'de' : 'German',
    'es' : 'Spanish',
    'eu' : 'Basque',
    'fr' : 'French',
    'gl' : 'Galician',
    'it' : 'Italian',
    'kr' : 'Korean',
    'nb' : 'Norwegian',
    'nl' : 'Dutch',
    'pl' : 'Polish',
    'pt' : 'Portuguese',
    'ru' : 'Russian',
    'sv' : 'Swedish',
    'tr' : 'Turkish',
    'zh-cn' : 'Chinese',
    'zh-tw' : 'Traditional Chinese'
}
